---
abstract: "Interfaces with AWS's SES service.\r"
author:
  - 'Rusty Conover <rusty@luckydinosaur.com>'
build_requires:
  Email::Sender::Simple: '0'
  Email::Simple: '0'
  Email::Simple::Creator: '0'
  MIME::Entity: '0'
  Test::Modern: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Amazon-SES
requires:
  AWS::Signature4: '0'
  Carp: '0'
  Email::Sender::Transport: '0'
  HTTP::Headers: '0'
  HTTP::Request::Common: '0'
  JSON::XS: '0'
  Kavorka: '0'
  LWP::UserAgent: '0'
  MIME::Base64: '0'
  Moo: '0'
  MooX::Types::MooseLike::Base: '0'
  Moops: '0'
  Time::Piece: '0'
  VM::EC2::Security::CredentialCache: '0'
  XML::Simple: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/rustyconover/amazon-ses/issues
  repository: git://github.com/rustyconover/amazon-ses.git
version: '0.02'
